### ISSUE TITLE
NO LIP_SP_VAL_annotations.json in the project

### ISSUE THREAD

**Issue by Zakeiswo** [ziwei-zh/CorrPM#1]
Hi, thanks for your code, here are some problem. I can't find LIP_SP_VAL_annotations.json in your project, but run_eval.sh have the code like:
`CS_PATH='/data/zzw/segment/data/lip/images_labels'
POSE_ANNO='/data/zzw/segment/data/lip/TrainVal_pose_annotations/LIP_SP_VAL_annotations.json'`

**Comment by ziwei-zh** [comment]
Yes, LIP_SP_VAL_annotations.json is not used in my project.
You can delete the line of POSE_ANNO in bash file, since only the parsing result is going to be evaluated and no pose annotations are needed.

**Comment by Zakeiswo** [comment]
thx

**Comment by Zakeiswo** [comment]
Sorry to bother you, would you mind sharing the LIP_SP_VAL_annotations.json with me.  And I want to use the file for other experiments.

**Comment by ziwei-zh** [comment]
I upload the json file in google drive, please refer to README.md.

**Comment by Zakeiswo** [comment]
Thank u very much.

**Comment by Zakeiswo** [comment]
Sorry to bother again, the google drive needs permission to access it.

**Comment by ziwei-zh** [comment]
Can you get access by this link:
https://drive.google.com/open?id=1OWx87t4ydnkT1RGGFM4lRpPW2D4jTzOx
