### ISSUE TITLE
How to test my own image if I dont have Human pose and edge info?

### ISSUE THREAD

**Issue by dragen1860** [ziwei-zh/CorrPM#4]
Dear author:
   Thanks for shareing the implementation!
   I doubt that How could i test on my own images, Since I dont have the pose and edge info in terms of json file? Thank you.

**Comment by ziwei-zh** [comment]
During inference, only the test image is needed. So you do not have to prepare the pose and edge information.

**Comment by dragen1860** [comment]
Yes, I noticed that. Thank you.
